// src/lib/components/WellReport.svelte
<script lang="ts">
	export let groups; // Declare the prop
	const getBGColor = (data: any) => {
		switch (data.pump) {
			case 'well':
				return `background-color: rgba(255, 99, 71, 0.5)`;
			case 'pressure':
				return `background-color: rgb(173, 175, 204)`;
			default:
				return ``;
		}
	};
	function doFormat(theDate: Date) {
		const options = {
			month: 'short' as 'short' | 'numeric' | '2-digit' | 'long' | 'narrow',
			day: 'numeric' as 'numeric' | '2-digit',
			hour: 'numeric' as 'numeric' | '2-digit',
			minute: 'numeric' as 'numeric' | '2-digit',
			second: 'numeric' as 'numeric' | '2-digit',
			hour12: true
		};

		return theDate.toLocaleString('en-US', options);
	}
</script>

<h3 class="center">Pumping Stats</h3>
<table>
	<thead>
		<tr>
			<th>Time</th>
			<th>Fragments</th>
			<th>Start-End</th>
			<th>Hours<br /> since</th>
			<th>When ended</th>
		</tr>
	</thead>
	<tbody>
		{#each groups as r, i (i)}
			<tr style={getBGColor(r)}>
				<td>{r.time}</td>
				<td>{r.frags}</td>
				<td>{r.dists}</td>
				<td>{r.sinceLastPump}</td>
				<td>{doFormat(r.when)}</td>
			</tr>
		{/each}
	</tbody>
</table>

<style>
	.center {
		text-align: center;
	}
	td {
		text-align: center;
	}
</style>

// src/components/well-report.jsx
import { format } from "date-fns"

const getBGColor = (data) => {
  
  switch (data.pump) {
    case "well":
      return { backgroundColor: "rgba(255, 99, 71, 0.5)" }
    case "pressure":
      return { backgroundColor: "rgb(173, 175, 204)" }
    default:
      return {}
  }
}

const WellReport = ({groups}) => {
  return (
    <div class="column">
      <h3 className="text-center">Pumping Stats</h3>
      <table striped bordered hover size="sm">
        <thead>
          <tr>
            <th>Time</th>
            <th>Fragments</th>
            <th>start-end</th>
            <th>Hours since last pump</th>
            <th>When ended</th>
          </tr>
        </thead>
        <tbody>
          {groups.map((r, i) => {
            return (
              <tr key={i} style={getBGColor(r)}>
                <td key={1}>{r.time}</td>
                <td key={2}>{r.frags}</td>
                <td key={3}>{r.dists}</td>
                <td key={4}>{r.sinceLastPump}</td>
                <td key={5}>{format(r.when, "MMM d, h:mm:ss a")}</td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}
export default WellReport
